In [1]:
import tensorflow as tf

ModuleNotFoundError: No module named 'tensorflow'

In [2]:
!pip install tensorflow

     |████████████████████████████████| 511.7 MB 638 bytes/s  0:00:014  |                                | 634 kB 248 kB/s eta 0:34:15     |█▌                              | 23.5 MB 3.1 MB/s eta 0:02:36     |███████████▉                    | 188.6 MB 5.2 MB/s eta 0:01:03     |███████████▉                    | 190.1 MB 5.1 MB/s eta 0:01:03     |███████████████████▋            | 314.4 MB 4.2 MB/s eta 0:00:48     |████████████████████▊           | 331.0 MB 876 kB/s eta 0:03:27     |███████████████████████▎        | 371.5 MB 4.3 MB/s eta 0:00:33     |█████████████████████████████▉  | 476.3 MB 1.0 MB/s eta 0:00:35     |███████████████████████████████▍| 502.8 MB 3.6 MB/s eta 0:00:03
     |████████████████████████████████| 42 kB 147 kB/s eta 0:00:011
     |████████████████████████████████| 65 kB 556 kB/s eta 0:00:011
     |████████████████████████████████| 2.4 MB 4.2 MB/s eta 0:00:01     |████▏                           | 307 kB 4.2 MB/s eta 0:00:01
     |████████████████████████████████| 123

In [5]:
import tensorflow as tf
import numpy as np

In [7]:
arr=np.array([[1,2,3,4],[4,5,6,0],[2,0,7,9],[3,7,4,2]])
gf=tf.data.Dataset.from_tensor_slices(arr)
for i in gf:
    print(i.numpy())

2022-07-06 22:38:11.827191: W tensorflow/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libcuda.so.1'; dlerror: libcuda.so.1: cannot open shared object file: No such file or directory
2022-07-06 22:38:11.827280: W tensorflow/stream_executor/cuda/cuda_driver.cc:269] failed call to cuInit: UNKNOWN ERROR (303)
2022-07-06 22:38:11.827337: I tensorflow/stream_executor/cuda/cuda_diagnostics.cc:156] kernel driver does not appear to be running on this host (cs-HP-Laptop-15-bs0xx): /proc/driver/nvidia/version does not exist
2022-07-06 22:38:11.861783: I tensorflow/core/platform/cpu_feature_guard.cc:193] This TensorFlow binary is optimized with oneAPI Deep Neural Network Library (oneDNN) to use the following CPU instructions in performance-critical operations:  AVX2 FMA
To enable them in other operations, rebuild TensorFlow with the appropriate compiler flags.


[1 2 3 4]
[4 5 6 0]
[2 0 7 9]
[3 7 4 2]


In [8]:
map(max,arr)

In [9]:
list(map(max,arr))

[4, 6, 9, 7]