In [2]:
import tensorflow as tf
vector1=tf.constant([10,10])
vector2=tf.constant([20,20])
tf.add(vector1,vector2)
v1=tf.constant([[2,5,1],[7,12,4],[19,5,6]])
v2=tf.constant([[12,4,11],[67,23,45],[71,11,10]])
v3=v1+v2
print(v3)

2022-07-06 22:50:38.993038: W tensorflow/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libcudart.so.11.0'; dlerror: libcudart.so.11.0: cannot open shared object file: No such file or directory
2022-07-06 22:50:38.993075: I tensorflow/stream_executor/cuda/cudart_stub.cc:29] Ignore above cudart dlerror if you do not have a GPU set up on your machine.


tf.Tensor(
[[14  9 12]
 [74 35 49]
 [90 16 16]], shape=(3, 3), dtype=int32)


2022-07-06 22:50:44.227649: W tensorflow/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libcuda.so.1'; dlerror: libcuda.so.1: cannot open shared object file: No such file or directory
2022-07-06 22:50:44.227702: W tensorflow/stream_executor/cuda/cuda_driver.cc:269] failed call to cuInit: UNKNOWN ERROR (303)
2022-07-06 22:50:44.227739: I tensorflow/stream_executor/cuda/cuda_diagnostics.cc:156] kernel driver does not appear to be running on this host (cs-HP-Laptop-15-bs0xx): /proc/driver/nvidia/version does not exist
2022-07-06 22:50:44.228091: I tensorflow/core/platform/cpu_feature_guard.cc:193] This TensorFlow binary is optimized with oneAPI Deep Neural Network Library (oneDNN) to use the following CPU instructions in performance-critical operations:  AVX2 FMA
To enable them in other operations, rebuild TensorFlow with the appropriate compiler flags.


In [4]:
import tensorflow as tf
list=[[1,2,3],[2,3,4],[4,5,6]]
rank=tf.constant([[0,1,3],[2,0,4],[5,1,0]])
c=tf.add(list,rank)
print(c)

tf.Tensor(
[[1 3 6]
 [4 3 8]
 [9 6 6]], shape=(3, 3), dtype=int32)
